// <auto-generated />
using System;
using EliteRestaurant.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EliteRestaurant.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EliteRestaurant.Core.Models.AttendanceDayValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("WorkDate")
                        .IsUnique();

                    b.ToTable("AttendanceDayValidations", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedReservationCount")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastVisitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredContactChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryPhone");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FridayShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MondayShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlySalaryUSD")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaturdayShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignInId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SundayShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThursdayShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TuesdayShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WednesdayShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SignInId")
                        .IsUnique()
                        .HasFilter("\"SignInId\" IS NOT NULL AND \"SignInId\" <> ''");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.EmployeeAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbsenceJustification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClockInStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAbsence")
                        .HasColumnType("boolean");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique();

                    b.ToTable("EmployeeAttendances", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.MoneyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountFc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderOriginType")
                        .HasColumnType("text");

                    b.Property<int?>("RelatedOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Type");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderRecordId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreparedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("PreparedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreparedByRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderRecordId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllergyNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ChangeGivenFc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChangeGivenUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerFulfillmentStatus")
                        .HasColumnType("text");

                    b.Property<string>("CustomerNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CustomerPaidFc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CustomerPaidUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeliveryFeeUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DiscountAmountUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("DiscountMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentAmountFc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentAmountUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PaymentConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentCurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentTiming")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReservationBookingId")
                        .HasColumnType("integer");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReservationGuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ServerId")
                        .HasColumnType("integer");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("TableId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.PayrollPaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsenceDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("AdvancesDeductedUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BonusFivePercentUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("LateDays")
                        .HasColumnType("integer");

                    b.Property<int>("LatePenaltyUnits")
                        .HasColumnType("integer");

                    b.Property<decimal>("MoneyGeneratedUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlySalaryUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetPayUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PaidToDateUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalDeductionUnits")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("PayrollPaymentRecords", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.PlacementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LayoutX")
                        .HasColumnType("integer");

                    b.Property<int>("LayoutY")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPartyCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("MergeClusterKey")
                        .HasColumnType("text");

                    b.Property<int>("MinPartyCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MergeClusterKey");

                    b.HasIndex("TableId")
                        .IsUnique();

                    b.ToTable("PlacementUnits", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Composition")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.ProductIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductIngredients", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.PublicMenuAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PublicMenuAssets", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.PublicMenuSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerMenuTagline")
                        .HasColumnType("text");

                    b.Property<string>("DefaultCurrencyDisplayMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoundingGrandTotal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoundingLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoundingSubtotal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ServicePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("SocialMedia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffLoginPasscode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxIdLegalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("TicketFooterText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UsdToFcRate")
                        .HasColumnType("numeric");

                    b.Property<string>("WebsiteDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PublicMenuSettings", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.ReservationBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CustomerProfileId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DepositAmountUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("DepositCurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DepositForfeited")
                        .HasColumnType("boolean");

                    b.Property<bool>("DepositPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<string>("ReservationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReservedFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("ReservedFor");

                    b.HasIndex("Status");

                    b.HasIndex("TableId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.ReservationEngagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<int>("PlacementUnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlannedEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReminderTwoHoursBeforeSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReservationBookingId")
                        .HasColumnType("integer");

                    b.Property<bool>("RotationOrOverstayFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlacementUnitId");

                    b.HasIndex("PlannedStartUtc");

                    b.HasIndex("ReservationBookingId");

                    b.HasIndex("Status");

                    b.HasIndex("TableId");

                    b.ToTable("ReservationEngagements", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.SalaryAdvance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric");

                    b.Property<int?>("AppliedPayrollMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("AppliedPayrollYear")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ForPayrollMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("ForPayrollYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GivenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryAdvances", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.SharedOrderDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Portal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "Portal", "UpdatedAtUtc");

                    b.ToTable("SharedOrderDrafts", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.SyncOutbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "QueuedAtUtc");

                    b.ToTable("SyncOutbox", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedServerId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedServerId");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.TabletSession", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeUniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Portal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignInId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Token");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("TabletSessions", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.WaitlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<int?>("QuotedWaitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("WaitlistEntries", (string)null);
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.EmployeeAttendance", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.OrderItem", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.OrderRecord", "OrderRecord")
                        .WithMany("Items")
                        .HasForeignKey("OrderRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EliteRestaurant.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderRecord");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.OrderRecord", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.Employee", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EliteRestaurant.Core.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Server");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.PayrollPaymentRecord", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.PlacementUnit", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.ProductIngredient", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EliteRestaurant.Core.Models.Product", "Product")
                        .WithMany("Ingredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.ReservationBooking", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.CustomerProfile", "CustomerProfile")
                        .WithMany()
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EliteRestaurant.Core.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomerProfile");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.ReservationEngagement", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.PlacementUnit", "PlacementUnit")
                        .WithMany()
                        .HasForeignKey("PlacementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EliteRestaurant.Core.Models.ReservationBooking", "ReservationBooking")
                        .WithMany()
                        .HasForeignKey("ReservationBookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EliteRestaurant.Core.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlacementUnit");

                    b.Navigation("ReservationBooking");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.SalaryAdvance", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.Table", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.Employee", "AssignedServer")
                        .WithMany()
                        .HasForeignKey("AssignedServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedServer");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.TabletSession", b =>
                {
                    b.HasOne("EliteRestaurant.Core.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.InventoryItem", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.OrderRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EliteRestaurant.Core.Models.Product", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
